name: carsigo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- NUEVAS DEPENDENCIAS DE FIREBASE ---
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.2.1

  # --- DEPENDENCIAS ANTERIORES (Supabase eliminada) ---
  cupertino_icons: ^1.0.8
  uuid: ^4.3.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
